stages:
  - build
  - deploy

build-frontend:
  stage: build
  image: node:22
  script:
    - apt-get update && apt-get install -y git
    - git submodule init
    - git submodule update
    - npm install
    - npm run build studio --configuration production
  artifacts:
    name: "dist-output"
    paths:
      - dist/studio

deploy-frontend:
  stage: deploy
  image: alpine
  dependencies:
    - "build-frontend"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv dist/studio studio
    - scp -r -o StrictHostKeyChecking=no studio $SERVER_USER@$SERVER_IP:/home/staginguser/public_html/
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo $PASSWORD | sudo -S nginx -s reload"