stages:
  - build

build-frontend:
  stage: build
  image: ghcr.io/cirruslabs/flutter:3.19.5
  script:
    - curl -fsSL https://fnm.vercel.app/install | bash
    - source ~/.bashrc
    - fnm use --install-if-missing 20
    - git submodule init
    - git submodule update
    - npm install
    - npm run build studio 