stages:
  - build
  - deploy

build-frontend:
  stage: build
  image: node:18.19.1

  script:
    - npm cache clean --force
    # - rm -rf node_modules package-lock.json
    # - npm install -g @angular/cli@15.0.3
    - npm cache clean --force
    - rm -rf node_modules package-lock.json
    - npm install
    - npm install @angular/cli
    - npm install @angular/compiler-cli
    - npm i sequential-workflow-designer
    # - npm install
    # - git submodule init
    # - git submodule update
    # - ng build @splenta/vezo
    # - ng build studio
  artifacts:
    name: "dist-output"
    paths:
      - dist/studio

deploy-frontend:
  stage: deploy
  image: alpine
  dependencies:
    - "build-frontend"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv dist/studio studio
    - scp -r -o StrictHostKeyChecking=no studio $SERVER_USER@$SERVER_IP:/home/staginguser/public_html/
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo $PASSWORD | sudo -S nginx -s reload"