stages:
  - build

build-frontend:
  stage: build
  image: ghcr.io/cirruslabs/flutter:3.19.5
  script:
    - curl -fsSL https://fnm.vercel.app/install | bash
    - export FNM_PATH="/root/.local/share/fnm"
    - export PATH="$FNM_PATH:$PATH"
    - eval "$(fnm env)"
    - fnm use --install-if-missing 20
    - git submodule init
    - git submodule update
    - npm install
    - npm run build studio 